### PR TITLE
chore(dev): add devcontainer configuration

### PR DESCRIPTION
**Pull request by AntoineDao**
This makes it easier to develop and run tests against an environment that has the right python virtualenv + a local speckle server + postgres + redis instance/

You can get started in VSCode by using `CTRL + SHIFT + P` (or something else on Max I guess :upside_down_face: ). You can find more info about VSCode devcontainers and how to use them [here](https://code.visualstudio.com/docs/remote/create-dev-container).

### CODE REVIEW

**Comment by AntoineDao** [comment]
Bump @izzylys for feedback :smile:

**Comment by izzylys** [comment]
hello! this took forever for me to review and I'm sorry pls don't hate me!!

I actually couldn't get docker working on my machine until v recently (stupid cpu settings that I couldn't figure out how to change) but now I can and I tried this and it's very cool and I like it a lot!!! very nice to be able to run tests without having to spin up a local server

happy to merge - just have a couple quick qs:
1. is there a reason for py 3.6? if not, I will bump to 3.9
2. are you on windows? if so, how are you deving from in the container without git EOL problems? lol adding a `.gitattributes` to force fix this worked fine for me tho so I will prob just pop that in as well 😅

**Comment by AntoineDao** [comment]
Erm... I use Linux :penguin:  because I'm not a savage :stuck_out_tongue:

No reason for python 3.6, feel free to change it to whatever :smile: 

What do you mean by git EOL?

**Comment by izzylys** [comment]
lololol sorry I'm 2 savage

ok sweet, I will update that then ^^

EOL = end of line -- git from within the container was freaking out and said _all_ files have been modified bc of the win vs linux line endings nonsense. but you're not a savage so you don't have the pleasure of experiencing this 😉

**Pull request merged**
