### PR TITLE
chore: upgrade to pydantic 2.0

### PR DESCRIPTION
**Pull request by mortenengen**
## Description & motivation

[`pydantic`](https://docs.pydantic.dev/latest/) recently released [v2.0](https://docs.pydantic.dev/latest/blog/pydantic-v2-final/). Among the [headlines](https://docs.pydantic.dev/latest/blog/pydantic-v2-alpha/#headlines) of v2.0 is a 5-50x speed increase. Since `pydantic` is used for parsing responses in `specklepy`, we might get a slight speed increase from updating our dependencies.

The changes suggested in this PR make `specklepy` compatible with `pydantic` v2.0. At least they ensure that the tests are all passing.

There are still some warnings raised when running the test suite, but apart from those already raised from `specklepy` these warnings are only related to methods that are schedule for removal in `pydantic` v3.0.

## Changes:

- Fields that are `Optional` in the models in `specklepy.api.models` are given default values.
- The configuration of `specklepy.transports.abstract_transport.AbstractTransport` is stored in the model attribute `model_config` instead of the configuration class `Config`.
- Deprecated model validation methods are replaced. This relates to `parse_obj` -> `model_validate` and `parse_raw` -> `model_validate_json`.
- The dependency in `pyproject.toml` is updated to `pydantic = "^2.0"`

## To-do before merge:

- [ ] Decide if it is necessary to replace calls to methods that are scheduled for removal in v3.0 to avoid warnings when running the test suite.
- [x] Update `poetry.lock`

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.

### CODE REVIEW

**Comment by mortenengen** [comment]
I updated `poetry.lock` to be able to run the circleci pipeline.

**Review by gjedlicska — APPROVED** [review]
Hey, thanks for the contribution Morten. While you are correct, that the models are used for parsing, the are not on the CPU heavy path. The parsing of the SpeckleBase models is not done with pydantic, and that is the most performance heavy operation.
This makes the migration less of a priority, since the gql requests are mostly IO bound.

I'll try to get around giving this a proper test before merging.

**Comment by mortenengen** [comment]
@gjedlicska: I have resolved some conflicts that appeared due to the latest changes to main. Please go ahead with your planned testing 😃

**Comment by mortenengen** [comment]
The decrease in code coverage (-0.01%) is an indirect decrease which happens because `test_stream_grant_permission` was removed in da83828. Since this test is removed, `UnsupportedException` is no longer covered by any of the tests.

**Comment by gjedlicska** [comment]
Hey @mortenengen 

thanks for the contribution :) I'm re-targeting this PR to a branch of mine, where i'm adding a few more migrations from deprecated methods.
I think these changes should be good to go for our next release cycle

**Pull request merged**
