### PR TITLE
Fix: also suppress TypeError during type checking.

### PR DESCRIPTION
**Pull request by RobClaessensRHDHV**
## Description & motivation

Currently an error is raised in below line, when an attempt is made to convert a given value to a float. In my case, this is a problem when I have a Union type hint that includes float, e.g. `Union[int, float, dict]`. During type checking, an iteration will be made over the types within the Union. Then, when the value is a dictionary, it will give a TypeError, which is currently not suppressed by the `contextlib.suppress()` call.

https://github.com/specklesystems/specklepy/blob/420c73f4844d124b1a813b16a2a2ee71a521bccd/src/specklepy/objects/base.py#L312

I agree that this Union type hint with both numeric types and a dictionary is not very common, but it still shouldn't give an error. By also suppressing TypeError, this is prevented.

## Changes:

TypeError is also suppressed. This will suppress the error and of course evaluate to False for a check of a dict value against a float type hint. It will evaluate to True once the dict type hint is reached, i.e. the given dict value passes the check against the total Union type hint.

## Validation of changes:

As said, in my case I had a Union type hint as `Union[float, dict]`. This gave an error when the given value was a dictionary. With this fix, that is prevented and the type check evaluates to True for a dictionary as input.

@gjedlicska

### CODE REVIEW

**Comment by RobClaessensRHDHV** [comment]
> Hey @RobClaessensRHDHV
> 
> thanks for the fix, would u mind adding a simple test case for this scenario in https://github.com/specklesystems/specklepy/blob/main/tests/unit/test_type_validation.py#L109 ?
> 
> Also pls update your branch with latest main. Thank you :)

@gjedlicska
Done and done!

**Comment by gjedlicska** [comment]
Perfect 😊

**Comment by RobClaessensRHDHV** [comment]
@gjedlicska Thanks for merging!

Will there be a quick patch including this fix?
We need it for an open pull request on our side.

**Comment by gjedlicska** [comment]
I just pushed one :)

**Pull request merged**
