### PR TITLE
Fix: Interoperability from Revit analytical to specklepy structural

### PR DESCRIPTION
**Pull request by RobClaessensRHDHV**
## Description & motivation

Update `speckle_type` of `SectionProfile` to match C#, update type hints with C# Enum values to int.

For the SectionProfile, a separate static variable e.g. STRUCTURAL_PROFILE could be created later, I now just made an easy fix. For the enumeration attributes, I believe they should be integer, as e.g. Revit pushes them as integers, not strings.

## Changes 

Section profile fix allows to properly deserialize `SectionProfile` objects.
The type hint fixes allow to properly receive the `Axis` and `Activity` objects.

## Validation of changes:

Deserialized Analytical Revit test streams with the proposed changes, which then works.

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

### CODE REVIEW

**Comment by RobClaessensRHDHV** [comment]
Sorry, had one incorrect change that broke the pipeline.
I reverted it, now it passes :)

**Comment by RobClaessensRHDHV** [comment]
@gjedlicska @itspatrickhe

**Comment by RobClaessensRHDHV** [comment]
Hi @gjedlicska,
Have you looked at the proposed changes?
I see that @knuttatutta has proposed [another PR](https://github.com/specklesystems/specklepy/pull/257/files) that also fixes the `axisType` issue, in a better way actually.
We can put the adjustments together in one PR if you like, but would be good to hear your opinion!

**Comment by gjedlicska** [comment]
Sorry, this slipped through the cracks.
@RobClaessensRHDHV

**Review by gjedlicska — APPROVED** [review]

**Pull request merged**
